name: Add Reviewer to Pull Request
on:
  pull_request_target:
    types: [opened]

jobs:
  add_reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add Reviewer
        run: |
          # Extract necessary information
          PR_NUMBER=$(echo "$GITHUB_REF" | awk -F'/' '{print $3}')
          REPO_OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 1)
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)

          # Define the reviewer(s) here, replace 'reviewer1' and 'reviewer2' with the actual GitHub usernames
          REVIEWER_LIST="robert-min"

          for REVIEWER in $REVIEWER_LIST; do
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.ROBERT_MIN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${PR_NUMBER}/requested_reviewers" \
              -d '{"reviewers":["'"$REVIEWER"'"]}'
          done
